//! Tiny `iDOT` fixtures (`tests/fixtures/idot/`, generated by `generate.py`
//! there, each a few hundred bytes) across every PNG color type and depth.
//!
//! For each fixture:
//! - the `png` crate (which ignores `iDOT`) must decode the raw scanlines to
//!   the SHA-256 the generator computed from the pixels it encoded — an
//!   independent ground truth for the fixture itself;
//! - zenpng must decode identically with and without threads (pixels,
//!   warnings, or error), default and strict;
//! - for raw-equivalent formats (RGB8/RGBA8/Gray8), zenpng's output must
//!   match that same hash;
//! - with `_dev`, the parallel path must complete exactly on the files the
//!   manifest marks `parallel_usable` (the size threshold is lowered so these
//!   tiny images qualify).

#![cfg(not(target_arch = "wasm32"))]

use std::path::PathBuf;

use sha2::{Digest, Sha256};
use zenflate::Unstoppable;
use zenpng::{PngDecodeConfig, decode};

struct Fixture {
    file: String,
    color_type: u8,
    bit_depth: u8,
    raw_sha256: Option<String>,
    serial_ok: bool,
    parallel_usable: bool,
}

fn dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/idot")
}

fn fixtures() -> Vec<Fixture> {
    let text = std::fs::read_to_string(dir().join("manifest.tsv")).unwrap();
    let v: Vec<Fixture> = text
        .lines()
        .skip(1)
        .map(|l| {
            let f: Vec<&str> = l.split('\t').collect();
            Fixture {
                file: f[0].into(),
                color_type: f[1].parse().unwrap(),
                bit_depth: f[2].parse().unwrap(),
                raw_sha256: (f[5] != "-").then(|| f[5].into()),
                serial_ok: f[6] == "1",
                parallel_usable: f[7] == "1",
            }
        })
        .collect();
    assert!(v.len() >= 40, "manifest too short");
    v
}

fn sha256_hex(b: &[u8]) -> String {
    Sha256::digest(b)
        .iter()
        .map(|x| format!("{x:02x}"))
        .collect()
}

/// Raw packed scanlines via the `png` crate, no transformations.
fn png_crate_raw(data: &[u8]) -> Result<Vec<u8>, png::DecodingError> {
    let mut dec = png::Decoder::new(std::io::Cursor::new(data));
    dec.set_transformations(png::Transformations::IDENTITY);
    let mut reader = dec.read_info()?;
    let mut buf = vec![0; reader.output_buffer_size().unwrap()];
    let info = reader.next_frame(&mut buf)?;
    buf.truncate(info.buffer_size());
    Ok(buf)
}

#[test]
fn tiny_idot_fixtures() {
    #[cfg(feature = "_dev")]
    zenpng::__set_idot_min_bytes(1);
    let can_parallel = std::thread::available_parallelism().map_or(1, |n| n.get()) >= 2;

    for fx in fixtures() {
        let path = dir().join(&fx.file);
        let data = std::fs::read(&path).unwrap();
        let name = &fx.file;

        // 1. Fixture ground truth, via a decoder that ignores iDOT.
        if let Some(expect) = &fx.raw_sha256 {
            let raw = png_crate_raw(&data).unwrap_or_else(|e| panic!("{name}: png crate: {e}"));
            assert_eq!(
                &sha256_hex(&raw),
                expect,
                "{name}: png crate disagrees with generator"
            );
        }

        #[cfg(feature = "_dev")]
        let before = zenpng::__idot_stats();
        for base in [PngDecodeConfig::default(), PngDecodeConfig::strict()] {
            let serial = decode(&data, &base.clone().with_max_threads(1), &Unstoppable);
            assert_eq!(serial.is_ok(), fx.serial_ok, "{name}: serial ok mismatch");
            for threads in [0usize, 2, 4] {
                let par = decode(&data, &base.clone().with_max_threads(threads), &Unstoppable);
                match (&serial, &par) {
                    (Ok(s), Ok(p)) => {
                        let (sb, pb) = (
                            s.pixels.copy_to_contiguous_bytes(),
                            p.pixels.copy_to_contiguous_bytes(),
                        );
                        assert!(sb == pb, "{name}: pixels differ (threads {threads})");
                        assert_eq!(s.warnings, p.warnings, "{name}: warnings differ");
                        // 3. Raw-equivalent formats: zenpng output == ground truth.
                        let raw_equiv = fx.bit_depth == 8 && matches!(fx.color_type, 0 | 2 | 6);
                        if raw_equiv && let Some(expect) = &fx.raw_sha256 {
                            assert_eq!(&sha256_hex(&pb), expect, "{name}: zenpng pixels wrong");
                        }
                    }
                    (Err(s), Err(p)) => assert_eq!(
                        format!("{:?}", s.error()),
                        format!("{:?}", p.error()),
                        "{name}: errors differ"
                    ),
                    _ => panic!(
                        "{name}: serial ok={} threads {threads} ok={}",
                        serial.is_ok(),
                        par.is_ok()
                    ),
                }
            }
        }
        #[cfg(feature = "_dev")]
        {
            let completed = zenpng::__idot_stats().0 - before.0;
            if fx.parallel_usable && can_parallel {
                assert!(completed > 0, "{name}: parallel path did not complete");
            } else {
                assert_eq!(completed, 0, "{name}: parallel path completed but must not");
            }
        }
        #[cfg(not(feature = "_dev"))]
        let _ = (fx.parallel_usable, can_parallel);
    }
}
